@baseurl = http://localhost:3000

POST {{baseurl}}/firebase/sendnNotification
content-type: application/json

{
    "registrationToken" : "add - fcm - token -  from - android",
    "title" : "Helloo",
    "message" : "Welcome Rathish"
}

