@baseurl = http://localhost:5000

POST {{baseurl}}/firebase/notification
content-type: application/json

{
    "registrationToken" : "​d3A4q57ES4ukw7VbPgvkbu",
    "message" : "Helloo",
    "options" : "notification_options"
}
